project_id = "oysfgyrtpdwokyvkjhcf"

[functions.process-watermark]
verify_jwt = false

[functions.send-watermarked-files]
verify_jwt = false

[functions.cleanup-old-files]
verify_jwt = false

[functions.download-file]
verify_jwt = false

[functions.auto-send-trusted]
verify_jwt = false

[functions.notify-pending-requests]
verify_jwt = false

[functions.trigger-webhook]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false
